web/controllers/authentication/models.py
# -*- encoding: utf-8 -*-
"""
Copyright (c) 2019 - present AppSeed.us
"""

from flask_login import UserMixin
from web import db, login_manager
from web.controllers.authentication.util import hash_pass


class Users(db.Model, UserMixin):
    __tablename__ = 'Users'
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(64), unique=True)
    email = db.Column(db.String(64), unique=True)
    password = db.Column(db.LargeBinary)

    def __init__(self, **kwargs):
        for property, value in kwargs.items():
            # depending on whether value is an iterable or not, we must
            # unpack it's value (when **kwargs is request.form, some values
            # will be a 1-element list)
            if hasattr(value, '__iter__') and not isinstance(value, str):
                # the ,= unpack of a singleton fails PEP8 (travis flake8 test)
                value = value[0]

            if property == 'password':
                value = hash_pass(value)  # we need bytes here (not plain str)

            setattr(self, property, value)

    def __repr__(self):
        return str(self.username)


@login_manager.user_loader
def user_loader(id):
    return Users.query.filter_by(id=id).first()


@login_manager.request_loader
def request_loader(request):
    username = request.form.get('username')
    user = Users.query.filter_by(username=username).first()
    return user if user else None

web/controllers/authentication/forms.py
# -*- encoding: utf-8 -*-
"""
Copyright (c) 2019 - present AppSeed.us
"""
from flask_wtf import FlaskForm
from wtforms import StringField as TextField, PasswordField
from wtforms.validators import Email, DataRequired

# login and registration


class LoginForm(FlaskForm):
    username = TextField('Username',
                         id='username_login',
                         validators=[DataRequired()])
    password = PasswordField('Password',
                             id='pwd_login',
                             validators=[DataRequired()])


class CreateAccountForm(FlaskForm):
    username = TextField('Username',
                         id='username_create',
                         validators=[DataRequired()])
    email = TextField('Email',
                      id='email_create',
                      validators=[DataRequired(), Email()])
    password = PasswordField('Password',
                             id='pwd_create',
                             validators=[DataRequired()])

web/__init__.py
from web.settings import (
    initialize_flask_app,
    initialize_plugins,
    register_blueprints,
    register_restful_api,
    configure_database,
    db,
    login_manager
)


def create_app(config):
    app = initialize_flask_app()
    app.config.from_object(config)

    with app.app_context():
        # Initialize Plugins
        initialize_plugins(app)
        # Register blueprints
        register_blueprints(app)
        register_restful_api(app)
        configure_database(app)

        return app

web/controllers/authentication/__init__.py
# -*- encoding: utf-8 -*-
"""
Copyright (c) 2019 - present AppSeed.us
"""

from flask import Blueprint

blueprint = Blueprint(
    'authentication_blueprint',
    __name__,
    url_prefix=''
)

web/controllers/authentication/routes.py
# -*- encoding: utf-8 -*-
"""
Copyright (c) 2019 - present AppSeed.us
"""

from flask import render_template, redirect, request, url_for
from flask_login import (
    current_user,
    login_user,
    logout_user
)

from web import db, login_manager
from web.controllers.authentication import blueprint
from web.controllers.authentication.forms import LoginForm, CreateAccountForm
from web.controllers.authentication.models import Users

from web.controllers.authentication.util import verify_pass


@blueprint.route('/')
def route_default():
    return redirect(url_for('authentication_blueprint.login'))


# Login & Registration

@blueprint.route('/login', methods=['GET', 'POST'])
def login():
    login_form = LoginForm(request.form)
    if 'login' in request.form:

        # read form data
        username = request.form['username']
        password = request.form['password']

        # Locate user
        user = Users.query.filter_by(username=username).first()

        # Check the password
        if user and verify_pass(password, user.password):

            login_user(user)
            return redirect(url_for('authentication_blueprint.route_default'))

        # Something (user or pass) is not ok
        return render_template('accounts/login.html',
                               msg='Wrong user or password',
                               form=login_form)

    if not current_user.is_authenticated:
        return render_template('accounts/login.html',
                               form=login_form)
    return redirect(url_for('home_blueprint.index'))


@blueprint.route('/register', methods=['GET', 'POST'])
def register():
    if request.host != 'localhost:5002' and request.host != '127.0.0.1:5002':
        return not_found_error('You cant go here')

    create_account_form = CreateAccountForm(request.form)
    if 'register' in request.form:

        username = request.form['username']
        email = request.form['email']

        # Check usename exists
        user = Users.query.filter_by(username=username).first()
        if user:
            return render_template('accounts/register.html',
                                   msg='Username already registered',
                                   success=False,
                                   form=create_account_form)

        # Check email exists
        user = Users.query.filter_by(email=email).first()
        if user:
            return render_template('accounts/register.html',
                                   msg='Email already registered',
                                   success=False,
                                   form=create_account_form)

        # else we can create the user
        user = Users(**request.form)
        db.session.add(user)
        db.session.commit()

        return render_template('accounts/register.html',
                               msg='User created please <a href="/login">login</a>',
                               success=True,
                               form=create_account_form)

    else:
        return render_template('accounts/register.html', form=create_account_form)


@blueprint.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('authentication_blueprint.login'))


# Errors

@login_manager.unauthorized_handler
def unauthorized_handler():
    return render_template('home/page-403.html'), 403


@blueprint.errorhandler(403)
def access_forbidden(error):
    return render_template('home/page-403.html'), 403


@blueprint.errorhandler(404)
def not_found_error(error):
    return render_template('home/page-404.html'), 404


@blueprint.errorhandler(500)
def internal_error(error):
    return render_template('home/page-500.html'), 500

web/controllers/home/__init__.py
# -*- encoding: utf-8 -*-
"""
Copyright (c) 2019 - present AppSeed.us
"""

from flask import Blueprint

blueprint = Blueprint(
    'home_blueprint',
    __name__,
    url_prefix=''
)

web/controllers/home/routes.py
# -*- encoding: utf-8 -*-
"""
Copyright (c) 2019 - present AppSeed.us
"""

from web.controllers.home import blueprint
from flask import render_template, request
from flask_login import login_required
from jinja2 import TemplateNotFound
import requests


@blueprint.route('/index')
@login_required
def index():
    capps = "http://localhost:5002/v1/capps"

    response = requests.get(capps)
    data = response.json()
    # return data
    return render_template('home/index.html', segment='index', page='dashboard', capps=data)


@blueprint.route('/<template>')
@login_required
def route_template(template):
    try:
        if not template.endswith('.html'):
            template += '.html'

        # Detect the current page
        segment = get_segment(request)

        page = segment.split('.')

        referrer = request.referrer

        # Serve the file (if exists) from app/templates/home/FILE.html
        return render_template("home/" + template, segment=segment, page=page[0], referrer=referrer)

    except TemplateNotFound:
        return render_template('home/page-404.html'), 404

    except:
        return render_template('home/page-500.html'), 500


# Helper - Extract current page name from request
def get_segment(request):
    try:
        segment = request.path.split('/')[-1]

        if segment == '':
            segment = 'index'

        return segment
    except:
        return None

web/templates/accounts/login.html
{% extends 'layouts/base-fullscreen.html' %}

{% block title %} Login {% endblock title %}

<!-- Specific CSS goes HERE -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

	<!-- Page content -->
	<!-- <div class="container"> -->
	<div class="row mt-6">

		<div class="col-xl-4 col-lg-5 col-md-7 mx-auto" >
			<div class="card z-index-0">
				<div class="card-header text-center pt-4">
					<h5>Sign In</h5>
					
					{% if msg %}
						<div class="alert alert-danger" role="alert">
							<strong>Oops!</strong> {{ msg | safe }}
						</div>
					{% else %}
					<span>
						sign in with your credentials
					</span>
					{% endif %}
				
				</div>
				
				<div class="card-body">
					<form role="form" method="post" action="">
						{{ form.hidden_tag() }}

						<div class="mb-3">
							{{ form.username(placeholder="Username",class="form-control") }}
						</div>
						<div class="mb-3">
							{{ form.password(placeholder="Password",class="form-control",type="password") }}
						</div>
						
						<div class="text-center">
							<button type="submit" name="login" class="btn btn-primary w-100 my-4 mb-2">Sign In</button>
						</div>

						<p class="text-sm mt-3 mb-0">Create new account? <a href="{{ url_for('authentication_blueprint.register') }}" target="_blank" class="text-dark font-weight-bolder">Sign Up</a></p>
					</form>
				</div>
			</div>
		</div>
	</div>
	<!-- </div> -->

{% endblock content %}

<!-- Specific JS goes HERE --> 
{% block javascripts %}{% endblock javascripts %}

web/templates/accounts/register.html
{% extends 'layouts/base-fullscreen.html' %}

{% block title %} Register {% endblock title %}

<!-- Specific CSS goes HERE -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

	<!-- Page content -->
	<div class="row mt-6">
		<div class="col-xl-4 col-lg-5 col-md-7 mx-auto" >
			<div class="card z-index-0">
				<div class="card-header text-center pt-4">
					<h5>Sign Up</h5>
					
					{% if msg %}
						<div class="alert alert-danger" role="alert">
							<strong>Oops!</strong> {{ msg | safe }}
						</div>
					{% else %}
						create your credentials
					{% endif %}
				</div>
				
				<div class="card-body">
					<form role="form text-left" method="post" action="">
						{{ form.hidden_tag() }}

						<div class="mb-3">
							{{ form.username(placeholder="Username",class="form-control") }}
						</div>
						<div class="mb-3">
							{{ form.email(placeholder="Email",class="form-control", type="email") }}
						</div>
						<div class="mb-3">
							{{ form.password(placeholder="Password",class="form-control",type="password") }}
						</div>
						
						<div class="text-center">
							<button type="submit" name="register" class="btn btn-primary w-100 my-4 mb-2">Sign Up</button>
						</div>
						<p class="text-sm mt-3 mb-0">Already have an account? <a href="{{ url_for('authentication_blueprint.login') }}" class="text-dark font-weight-bolder">Sign In</a></p>
					</form>
				</div>
			</div>
		</div>
	</div>

{% endblock content %}

<!-- Specific JS goes HERE --> 
{% block javascripts %}{% endblock javascripts %}

web/templates/home/logs.html
{% extends 'layouts/base.html' %}

{% block title %} Logs {% endblock title %}

<!-- Specific CSS goes HERE -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}
	<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>

	<div class="container-fluid py-4">
		<div class="row mb-3">
			<div class="col-lg-12 mb-lg-0 mb-4">
				<div class="card mb-4">
					<div class="card-header pb-0">
						<div class="row">
							<div class="col-lg-4">
								<div class="form-group">
									<label for="" class="text-primary">App Source</label>
									<select id="select_app" class="form-control form-control-lg">
									</select>
								</div>
							</div>
							<div class="col-lg-8" >
								<div class="form-group" style="float: right;" >
									<label for="" class="text-primary">Files</label>
									<select id="select_log_opt" class="form-control form-control-lg" style="width: 300px;">
									</select>
								</div>
							</div>
							
						</div>
						<hr class="bg-gradient-dark">
						<button id="load_more_down" class="btn btn-outline-primary btn-sm mb-0 me-3">load more</button>
						
					</div>
					<div class="card-body pb-0">
						<textarea id="content" class="form-control" style="width: 100%; white-space: pre;
								overflow-wrap: normal;
								overflow-x: scroll;" rows=20 disabled>
						</textarea>
						
						<hr class="bg-gradient-dark">
						<div class="row">
							<div class="col-lg-12">
								<div class="form-group form-check form-switch">
									<input type="checkbox" class="form-check-input" id="is_tail" name="is_tail">
            						<span class="text-primary">Load Continuously</span> | Will refresh in <span id="tail_counter"></span> second(s)
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>

		
		
		{% include "includes/footer.html" %}

	</div>


{% endblock content %}

<!-- Specific JS goes HERE -->
{% block javascripts %}
	<script>
		let base_url = window.location.origin;
		let app_name = localStorage.getItem("app_name") ? localStorage.getItem("app_name") : "indonesia";
		let file_index = localStorage.getItem("file_index") ? localStorage.getItem("file_index") : 0;
		let tail_counter = 0;
		let tail_counter_interval = null;

		let type = 'default';
		let line_top = 0;
		let line_bottom = 0;
		let total_lines = null;
		let tail_interval = null;

		function get_app() {
			$('#loader').show();
			$.get( base_url + "/v1/capps", function( data ) {
				var select_el = document.getElementById('select_app');
				var inner = ``;
				for (var i=0; i<data.data.length; i++) {
				if (app_name == data.data[i]) inner += `<option value="`+ data.data[i] +`" selected="true">` + data.data[i] + `</option>`
				else inner += `<option value="`+ data.data[i] +`">` + data.data[i] + `</option>`
				}
				select_el.innerHTML = inner;
			})
		}

		function every_five() {
			tail_counter = (tail_counter + 1) % 5;
			var tail_counter_el = document.getElementById('tail_counter');
			tail_counter_el.innerHTML = (5-tail_counter);
		}

		function get_content(line_num) {
			$('#loader').show();
			$.get( base_url + "/v1/logs/" + app_name + "/" + type + "/" + file_index + "/" + line_num, function( data ) {
				tail_counter = 0;

				if (tail_counter_interval) {
					clearInterval(tail_counter_interval)
				}

				if (tail_is_selected())
					tail_counter_interval = setInterval(every_five, 1000)

					var select_el = document.getElementById('select_log_opt');
					var inner = ``;
					for (var i=0; i<data.data.list.length; i++) {
						if (file_index == i)
							inner += `<option selected="true" value="`+ i +`">` + data.data.list[i] + `</option>`
						else
							inner += `<option value="`+ i +`">` + data.data.list[i] + `</option>`
					}

			$('#content').val(data.data.content);

			if (!line_num) {
				if (data.data.total_lines > 50)
					line_top = data.data.total_lines - 50;

				line_bottom = data.data.total_lines;
				total_lines = data.data.total_lines;
				}

				select_el.innerHTML = inner;

				$('#loader').hide();
			})
		}

		function update_select_app(app_name_) {
			localStorage.setItem("app_name", app_name_);
			app_name = app_name_;
			get_content(0);
		}

		function update_select_file(index) {
			localStorage.setItem("file_index", index);
			file_index = index;
		}

		$('#select_app').on('change', function() {
			update_select_app($('#select_app').val());
		});

		$('#select_log_opt').on('change', function() {
			update_select_file($('#select_log_opt').val());
			get_content_default();
		});

		$('#load_more_up').on('click', function() {
			if (line_top > 50)
				line_top -= 50;
			else if (line_top > 0)
				line_top = 0;

			get_content(line_top+50);
		});

		$('#load_more_down').on('click', function() {
			if (line_top + 50 < total_lines)
				line_top += 50;
			else
				line_top = total_lines - 50;
			get_content(line_top+50);
		});

		function tail_is_selected() {
		if (document.getElementById('is_tail').checked)
			return true;
		else return false;
		}

		function get_content_default() {
			get_content(0);
		}

		function tail_start() {
			tail_interval = setInterval( get_content_default, 5000 );
			tail_counter_interval = setInterval(every_five, 1000)
		}

		function tail_stop() {
			clearInterval(tail_interval);
			clearInterval(tail_counter_interval)
			var tail_counter_el = document.getElementById('tail_counter');
			tail_counter_el.innerHTML = '';
		}

		$('#is_tail').click(function() {
			if (tail_is_selected()) {
				tail_start();
			} else {
				tail_stop();
			}
		});

		$(function() {
			get_app();
			get_content_default();
		});
	</script>

	<script src="/static/assets-v2/js/soft-ui-dashboard.min.js?v=1.0.7"></script>
{% endblock javascripts %}

web/templates/home/page-403.html
{% extends 'layouts/base-fullscreen.html' %}

{% block title %} Error 403 {% endblock title %}

<!-- Specific CSS goes HERE -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

		<!-- Page content -->
		<div class="container mt--8 pb-5 mb-12">
			<div class="row justify-content-center">
				<div class="col-lg-5 col-md-7">
					<div class="card bg-secondary shadow border-0">
						<div class="card-header bg-transparent pb-5">

							<div class="text-muted text-center mt-2 mb-3">
								<h1 class="text-gradient text-primary">403</1>     
							</div>

							<div class="text-center text-white mb-4">
								Access denied - Please authenticate <a href="/login">Login</a>
							</div>

						</div>
					</div>
				</div>
			</div>
		</div>


{% endblock content %}

<!-- Specific JS goes HERE --> 
{% block javascripts %}{% endblock javascripts %}

web/templates/home/page-404.html
{% extends 'layouts/base-fullscreen.html' %}

{% block title %} Error 404 {% endblock title %}

<!-- Specific CSS goes HERE -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

		<!-- Page content -->
		<div class="container mt--8 pb-5 mb-12">
			<div class="row justify-content-center">
				<div class="col-lg-5 col-md-7">
					<div class="card bg-secondary shadow border-0">
						<div class="card-header bg-transparent pb-5">

							<div class="text-muted text-center mt-2 mb-3">
								<h1 class="text-gradient text-primary">404</1>     
							</div>

							<div class="text-center text-white mb-4">
								Page not found - <a href="/">Home</a>
							</div>

						</div>
					</div>
				</div>
			</div>
		</div>

{% endblock content %}

<!-- Specific JS goes HERE --> 
{% block javascripts %}{% endblock javascripts %}

web/templates/home/page-500.html
{% extends 'layouts/base-fullscreen.html' %}

{% block title %} Error 404 {% endblock title %}

<!-- Specific CSS goes HERE -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

		<!-- Page content -->
		<div class="container mt--8 pb-5 mb-12">
			<div class="row justify-content-center">
				<div class="col-lg-5 col-md-7">
					<div class="card bg-secondary shadow border-0">
						<div class="card-header bg-transparent pb-5">

							<div class="text-muted text-center mt-2 mb-3">
								<h1 class="text-gradient text-primary">500</1>     
							</div>

							<div class="text-center text-white mb-4">
								Server error, please contact support - <a href="/">Home</a>.
							</div>

						</div>
					</div>
				</div>
			</div>
		</div>

{% endblock content %}

<!-- Specific JS goes HERE --> 
{% block javascripts %}{% endblock javascripts %}

web/templates/home/task-history.html
{% extends 'layouts/base.html' %}

{% block title %} Tasks {% endblock title %}

{% block content %}
	<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>

	<div class="container-fluid py-4">
		<div class="row mb-3">
			<div class="col-lg-12 mb-lg-0 mb-4">
				<div class="card mb-4">
					<div class="card-header pb-0">
						<h6>History of Task : <span id="task_name" class="text-primary"></span></h6>
						<a href="{{ referrer|default('/tasks.html') }}" class="btn btn-secondary btn-sm mb-0 me-3">Back</a>
						<hr>
					</div>
					<div class="card-body px-0 pt-0 pb-2">
						<div class="table-responsive p-4">
							<table class="table align-items-center justify-content-center mb-0">
								<thead>
									<tr>
										<th class="text-uppercase text-dark text-xs font-weight-bolder opacity-7 ps-2">No</th>
										<th class="text-uppercase text-dark text-xs font-weight-bolder opacity-7 ps-2">ID</th>
										<th class="text-uppercase text-dark text-xs font-weight-bolder opacity-7 ps-2">Status</th>
										<th class="text-uppercase text-dark text-xs font-weight-bolder opacity-7 ps-2">Started</th>
										<th class="text-uppercase text-dark text-xs font-weight-bolder opacity-7 ps-2">Runtime (seconds)</th>
										<th class="text-uppercase text-dark text-xs font-weight-bolder opacity-7 ps-2">Result</th>
									</tr>
								</thead>
								<tbody id="result"></tbody>
								<tbody>
									<tr>
										<td colspan="6" align="center">
											<hr>
											<button class="btn btn-outline-primary btn-sm mb-0 me-3" id="load_more">load more</button>
										</td>
									</tr>
								</tbody>
							</table>
						</div>
					</div>
				</div>
			</div>
		</div>

		{% include "includes/footer.html" %}

	</div>

{% endblock content %}



<!-- Specific JS goes HERE -->
{% block javascripts %}
	<script>
		let base_url = window.location.origin;
		let page = 1
		let app_name = localStorage.getItem("app_name") ? localStorage.getItem("app_name") : "indonesia";

		function getBg(status) {
			if (status === "STARTED")
				return "bg-info";
			if (status === "FAILURE" || status === "REVOKED")
				return "bg-danger"
			if (status === "SUCCESS")
				return "bg-success";
		}

		function terminate(task_id) {
			$.ajax({
			url: base_url + "/v1/ctask/"+ app_name + "/" + task_id + "/terminate",
			type: 'DELETE',
			success: function(data) {
			location.reload()
			}
			});
		}

		function titleCase(str) {
		str = str.toLowerCase().split(' ');

		for (var i = 0; i < str.length; i++) {
			str[i] = str[i].charAt(0).toUpperCase() + str[i].slice(1);
		}

		return str.join(' ');
		}

		function setTaskNameTitle(task_name) {
			let el = document.getElementById("task_name");
			el.innerHTML = el.innerHTML + task_name
		}

		function loadMore(task_name) {
			$.get( base_url + "/v1/ctask/"+ app_name + "/" + task_name +"/history/" + page, function( data ) {
				let keys = Object.keys(data.data);

				for (let i = 0; i < keys.length; i++) {
					if (i == 0) {
						let friendly_name = titleCase(data.data[keys[i]].name.split('.').slice(-1)[0].replace('_', ' '));
						setTaskNameTitle(friendly_name);
					}

					let el = document.getElementById("result");
					el.innerHTML = el.innerHTML +
					`
					<tr>
						<td>
							<div class="d-flex px-2 py-1">
								<div class="d-flex flex-column justify-content-center">
									<span class="name mb-0 text-sm">`+ ((i + 1) + ((page - 1) * 5)) + `</span>
								</div>
							</div>
							
						</td>
						<td>
							<div class="media align-items-center">
								<div class="media-body">
									<span class="name mb-0 text-sm text-primary"><dt>`+ data.data[keys[i]].uuid +`</dt></span>
								</div>
							</div>
						</td>
						<td>
							<span class="badge badge-sm `+getBg(data.data[keys[i]].state)+`">
								<span class="status">`+ data.data[keys[i]].state +`</span>
							</span>
						</td>
						<td>
							<span class="name mb-0 text-sm">`+ new Date(data.data[keys[i]].started * 1000) + `</span>
						</td>
						<td>
							<span class="name mb-0 text-sm">
							`+ (data.data[keys[i]].runtime ? data.data[keys[i]].runtime.toFixed(3) : "---------") +`
							</span>
						</td>
						<td>
							<span class="name mb-0 text-sm">
							`+ (data.data[keys[i]].result ? data.data[keys[i]].result : "--------")+`
							</span>
						</td>
					</tr>

					`

				}

				page = page + 1;
			});
		}

		$(function() {
			const queryString = window.location.search;
			const urlParams = new URLSearchParams(queryString);
			const task_name = urlParams.get('task_name')
			loadMore(task_name)

			$("#load_more").click(function() {
				loadMore(task_name)
			});
		});
  	</script>

	<script src="/static/assets-v2/js/soft-ui-dashboard.min.js?v=1.0.7"></script>
{% endblock javascripts %}

web/templates/includes/footer-fullscreen.html
<footer class="footer py-1 mt-8">
	<div class="container">
		<div class="row">
			<div class="col-lg-8 mb-3 mx-auto text-center">
				<a href="javascript:;" target="_blank" class="text-white me-xl-5 me-3 mb-sm-0 mb-2">
					Company
				</a>
				<a href="javascript:;" target="_blank" class="text-white me-xl-5 me-3 mb-sm-0 mb-2">
					About Us
				</a>
				<a href="javascript:;" target="_blank" class="text-white me-xl-5 me-3 mb-sm-0 mb-2">
					Team
				</a>
				<a href="javascript:;" target="_blank" class="text-white me-xl-5 me-3 mb-sm-0 mb-2">
					Products
				</a>
				<a href="javascript:;" target="_blank" class="text-white me-xl-5 me-3 mb-sm-0 mb-2">
					Blog
				</a>
			</div>
		</div>
		<div class="row">
			<div class="col-8 mx-auto text-center">
				<p class="mb-0 text-white">
					Copyright © 
					<script>
						document.write(new Date().getFullYear())
					</script>
					<strong>Celery Dashboard.</strong>
				</p>
			</div>
		</div>
	</div>
</footer>

web/templates/includes/footer.html
<footer class="footer pt-10">
	<hr>
	<div class="container-fluid">
		<div class="row align-items-center justify-content-lg-between">
			<div class="col-lg-6 mb-lg-0 mb-4">
				<div class="copyright text-center text-sm text-muted text-lg-start">
					Copyright© 
					<script>
						document.write(new Date().getFullYear())
					</script>,
					made with <i class="fa fa-heart" style="color: #ea0606;"></i> by
					<a href="#" class="font-weight-bold" target="_blank">Developer</a>
					for a better web.
				</div>
			</div>
		</div>
	</div>
</footer>

web/templates/includes/navigation.html
<nav class="navbar navbar-main navbar-expand-lg px-0 mx-4 shadow-none border-radius-xl" id="navbarBlur" navbar-scroll="true">
	<div class="container-fluid py-1 px-3">
		<nav aria-label="breadcrumb">
			<ol class="breadcrumb bg-transparent mb-0 pb-0 pt-1 px-0 me-sm-6 me-5">
				<li class="breadcrumb-item text-sm"><a class="opacity-5 text-dark" href="javascript:;">Pages</a></li>
				<li class="breadcrumb-item text-sm text-dark active" aria-current="page">{{ page }}</li>
			</ol>
			<h6 class="font-weight-bolder mb-0">{{ page.capitalize() }}</h6>
		</nav>
		<div class="collapse navbar-collapse mt-sm-0 mt-2 me-md-0 me-sm-4" id="navbar">
			<div class="ms-md-auto pe-md-3 d-flex align-items-center">
				<div class="input-group"></div>
			</div>
			<ul class="navbar-nav  justify-content-end">
				<li class="nav-item d-flex align-items-center">
					<a class="btn btn-outline-primary btn-sm mb-0 me-3" href="{{ url_for('authentication_blueprint.logout') }}">Sign Out</a>
				</li>
			</ul>
		</div>
	</div>
</nav>

web/templates/includes/scripts.html
<script src="/static/assets-v2/vendor/jquery/dist/jquery.min.js"></script>
<script src="/static/assets-v2/js/core/popper.min.js"></script>
<script src="/static/assets-v2/js/core/bootstrap.min.js"></script>
<script src="/static/assets-v2/js/plugins/perfect-scrollbar.min.js"></script>
<script src="/static/assets-v2/js/plugins/smooth-scrollbar.min.js"></script>